name: Build and Push Docker Image

on:
  # 当代码推送到 main 分支时触发工作流
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # 检出代码到工作目录
        uses: actions/checkout@v3

      - name: Compress app file
        # 压缩 app 文件为 app.zip
        run: zip -r app.zip app
        working-directory: .

      - name: Set up Docker Buildx
        # 设置 Docker Buildx 以支持多平台构建
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        # 登录到 Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        # 构建并推送 Docker 镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          # 指定镜像标签
          tags: beijixingxing/hajimi:latest
          # 推送到 Docker Hub
          push: true

  sync-fork: # 定义一个名为 sync-fork 的任务
    runs-on: ubuntu-latest # 指定运行此任务的操作系统环境

    steps: # 定义任务中的步骤
      - name: Checkout repository # 步骤的名称：检出仓库
        # 使用 actions/checkout@v3 这个 action 来检出代码
        uses: actions/checkout@v3
        with:
          # 获取完整的提交历史，以便进行准确的比较和合并
          fetch-depth: 0

      - name: Set up Git # 步骤的名称：设置 Git
        # 运行脚本来配置 Git 用户名和邮箱
        run: |
          git config user.name "beijixingxing" # 设置 Git 用户名为 beijixingxing
          git config user.email "yunxi815@gmail.com" # 设置 Git 邮箱为 yunxi815@gmail.com

      - name: Add upstream remote # 步骤的名称：添加上游仓库的远程地址
        # 运行脚本来添加一个名为 upstream 的远程仓库，指向原始的上游仓库
        run: |
          git remote add upstream https://github.com/wyeeeee/hajimi.git # 设置上游仓库为 https://github.com/wyeeeee/hajimi.git

      - name: Fetch upstream changes # 步骤的名称：获取上游仓库的更改
        # 运行脚本来从上游仓库获取最新的提交和分支信息
        run: git fetch upstream

      - name: Merge upstream changes # 步骤的名称：合并上游仓库的更改
        # 运行脚本来将上游仓库的 main 分支合并到当前分支
        run: git merge upstream/main

      - name: Push changes to fork # 步骤的名称：推送更改到 fork 仓库
        # 运行脚本来将合并后的更改推送到当前仓库的 main 分支
        env:
          # 设置环境变量 GITHUB_TOKEN，用于进行推送操作
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
